import {
    GET_APPOINTMENT_OF_DOCTOR, GET_APPOINTMENT_OF_USER_FOLLOW_DOCTOR, GET_CATEGORY_PACKAGE, GET_CATEGORY_PACKAGE_BY_ID,
    GET_DOCTOR_FOLLOW_SPECIALTY, GET_DOCTORS, GET_DOCTORS_BY_ID, GET_INFOR_MAKE_APPOINTMENT, GET_MEDICAL_PACKAGE, GET_MEDICAL_PACKAGE_BY_ID,
    GET_MEDICAL_PACKAGE_FOLLOW_CATEGORY, UPDATE_STATUS_APPOINTMENT
} from "../utils/routeUrlApi";

// R1:admin, R2:doctor, R3:user, R4:staff
const ROLE_PERMISSIONS = {
    //admin: full quyền nên mặc định được next()
    R2: [GET_INFOR_MAKE_APPOINTMENT, GET_APPOINTMENT_OF_DOCTOR, UPDATE_STATUS_APPOINTMENT, GET_CATEGORY_PACKAGE, GET_CATEGORY_PACKAGE_BY_ID,
        GET_DOCTORS, GET_DOCTORS_BY_ID, GET_DOCTOR_FOLLOW_SPECIALTY, GET_APPOINTMENT_OF_USER_FOLLOW_DOCTOR, GET_MEDICAL_PACKAGE, GET_MEDICAL_PACKAGE_BY_ID,
        GET_MEDICAL_PACKAGE_FOLLOW_CATEGORY
    ], // bác sĩ
    R4: [GET_INFOR_MAKE_APPOINTMENT, GET_APPOINTMENT_OF_DOCTOR, UPDATE_STATUS_APPOINTMENT, GET_CATEGORY_PACKAGE, GET_CATEGORY_PACKAGE_BY_ID,
        GET_DOCTORS, GET_DOCTORS_BY_ID, GET_DOCTOR_FOLLOW_SPECIALTY, GET_APPOINTMENT_OF_USER_FOLLOW_DOCTOR, GET_MEDICAL_PACKAGE, GET_MEDICAL_PACKAGE_BY_ID,
        GET_MEDICAL_PACKAGE_FOLLOW_CATEGORY
    ], // nhân viên
    R3: [GET_INFOR_MAKE_APPOINTMENT, CREATE_APPOINTMENT, GET_APPOINTMENT_OF_USER, GET_CATEGORY_PACKAGE, GET_CATEGORY_PACKAGE_BY_ID,
        GET_DOCTORS, GET_DOCTORS_BY_ID, GET_DOCTOR_FOLLOW_SPECIALTY, GET_MEDICAL_PACKAGE, GET_MEDICAL_PACKAGE_BY_ID,
        GET_MEDICAL_PACKAGE_FOLLOW_CATEGORY
    ] // User thường không có quyền quản trị
};

const BLACKIST = [] // những route nào có trong đây không cần đăng nhập vẫn truy cập được
